In [30]:
import pandas as pd
import numpy as np

n = ['image', 'blank1', 'state', 'blank2', 'truth_x', 'truth_y', 'blank3', 'estimate_x', 'estimate_y', 'blank4', 'error']
df = pd.read_csv('C:/Users/ployw/OneDrive/Desktop/Kyutech/Lab/Thesis/Result/Pupil detection/D2 Data set/Result Files/AlexNet/result.csv',header = None,names=n)
df

image  blank1  state  blank2  truth_x  \
0       ../VDO_resize/kan1/2017052212_0/0.png     NaN      0     NaN     55.0   
1       ../VDO_resize/kan1/2017052212_0/1.png     NaN      1     NaN     54.0   
2       ../VDO_resize/kan1/2017052212_0/2.png     NaN      1     NaN     54.0   
3       ../VDO_resize/kan1/2017052212_0/3.png     NaN      0     NaN     55.0   
4       ../VDO_resize/kan1/2017052212_0/4.png     NaN      1     NaN     55.0   
...                                       ...     ...    ...     ...      ...   
1955  ../VDO_resize/kan1/2017052212_48/35.png     NaN      0     NaN     62.0   
1956  ../VDO_resize/kan1/2017052212_48/36.png     NaN      0     NaN     62.0   
1957  ../VDO_resize/kan1/2017052212_48/37.png     NaN      0     NaN     63.0   
1958  ../VDO_resize/kan1/2017052212_48/38.png     NaN      0     NaN     63.0   
1959  ../VDO_resize/kan1/2017052212_48/39.png     NaN      0     NaN     62.0   

      truth_y  blank3  estimate_x  estimate_y  blank4     error  
0        42.0     NaN   53.872128   39.189598     NaN  3.028276  
1        43.0     NaN   57.410339   36.565945     NaN  7.281997  
2        43.0     NaN   57.768364   36.625847     NaN  7.404755  
3        42.0     NaN   53.428246   40.663277     NaN  2.063308  
4        42.0     NaN   57.114346   37.281219     NaN  5.170817  
...       ...     ...         ...         ...     ...       ...  
1955     47.0     NaN   60.328598   45.846176     NaN  2.030984  
1956     47.0     NaN   59.982807   45.862232     NaN  2.315941  
1957     47.0     NaN   60.117233   45.143970     NaN  3.428584  
1958     47.0     NaN   60.092697   44.636337     NaN  3.746907  
1959     47.0     NaN   60.204613   44.613712     NaN  2.986266  

[1960 rows x 11 columns]

In [31]:
df["error"].mean()

8.589648635603924

In [32]:
model_name = ['VGG16+Dropout','VGG16','VGG16+Batch Normalization','Xception+Dropout','Xception','AlexNet']
print(model_name)

['VGG16+Dropout', 'VGG16', 'VGG16+Batch Normalization', 'Xception+Dropout', 'Xception', 'AlexNet']


In [41]:
print(model_name[0])

VGG16+Dropout


In [48]:
mean = np.array([['',''],['',''],['',''],['',''],['',''],['','']])
print(mean[0][0])
for i in range(6):
    mean[i][0] = model_name[i]
print(mean)


[['V' '']
 ['V' '']
 ['V' '']
 ['X' '']
 ['X' '']
 ['A' '']]


In [52]:
mean = np.empty([6,2])
print(mean)
for i in range(6):
    for j in range(2):
        mean[i][j] = str(mean[i][j])
print(mean)

for k in range(6):
    mean[k][0] = model_name[k]
print(mean)

[[1.50661701e-312 0.00000000e+000]
 [1.50661701e-312 0.00000000e+000]
 [1.50661701e-312 0.00000000e+000]
 [2.10077583e-312 0.00000000e+000]
 [2.10077583e-312 0.00000000e+000]
 [2.29175545e-312 0.00000000e+000]]
[[1.50661701e-312 0.00000000e+000]
 [1.50661701e-312 0.00000000e+000]
 [1.50661701e-312 0.00000000e+000]
 [2.10077583e-312 0.00000000e+000]
 [2.10077583e-312 0.00000000e+000]
 [2.29175545e-312 0.00000000e+000]]


ValueError: could not convert string to float: 'VGG16+Dropout'

In [50]:
for i in range(6):
    mean[i][0] = model_name[i]
print(mean)

ValueError: could not convert string to float: 'VGG16+Dropout'

In [38]:
mean = np.empty([6,2])
print(mean)
for i in range(6):
    for j in range(2):
        mean[i][j] = "1"
print(mean)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
mean[0][0] = "hello"

ValueError: could not convert string to float: 'hello'

In [19]:
for i in range(len(model_name)):
    mean[i][0] = str(model_name[i])

print(mean)

ValueError: could not convert string to float: 'VGG16+Dropout'